### PR TITLE
improve & fix

### PR DESCRIPTION
**Pull request by watcharapon**
[fix]
1. scrollbar of main page is disappear after close search popup
[approvement]
2. make button print of picking same as other such as print invoice.
     - click  -> print immedialy | select template
3. make button print of purchase order same as other such as print invoice.
4. Document module can't select field document.
5. reset empty condition ([]) if view mode is page
     - if empty condition "[]" is sent to search function  (model.search) it will get the error

### CODE REVIEW

**Comment by songpon** [comment]
for report improvement will discuss with Bank Wirat
Still not merge yet

**Comment by watcharapon** [comment]
I discussed with Wirat before. He agree to keep concept to print form the same way. Anyhow we can check with him tomorrow.

**Comment by songpon** [comment]
I got Idea from Nueng  , she like this way 
image

**Comment by watcharapon** [comment]
For the print button we will discuss after now I just reverse to the old one because we need to merge another to stable 3.1 ( I will do it myself)

**Pull request merged**
